on:
  workflow_dispatch:

jobs:
  send_datadog_metrics:
    runs-on: ubuntu-latest
    name: Collects Circle CI metrics and sends them to DataDog
    steps:
      - name: Fetch Circle CI Insights Summary
        id: fetch
        uses: jpdillingham/circleci-insights-summary@v0.2
        with:
          api-key: ${{ secrets.CIRCLE_CI_API_KEY }}
          project-slug: github/jpdillingham
          reporting-window: last-24-hours
      # Use the output from the `hello` step
      - name: Dump output
        run: echo "The time was ${{ steps.fetch.outputs.circleci.summary.json }}"