on:
  workflow_dispatch:

jobs:
  send_datadog_metrics:
    runs-on: ubuntu-latest
    name: Collects Circle CI metrics and sends them to DataDog
    steps:
      - name: Fetch Circle CI Insights Summary
        id: fetch
        uses: jpdillingham/circleci-insights-summary@v0.5
        with:
          api-key: ${{ secrets.CIRCLE_CI_API_KEY }}
          project-slug: github/jpdillingham
          reporting-window: last-24-hours
      - name: Dump output
        run: echo "summary ${{ steps.fetch.outputs.summary }} success rate ${{ steps.fetch.outputs.org_data-trends-success_rate }}"